name: ChunkEntityLimiter
version: '${project.version}'
main: es.ponnythelight.chunkentitylimiter.ChunkEntityLimiter
api-version: 1.19
authors: [ PonnyTheLight ]
description: Limit entitys in a Minecraft chunk.
website: https://discord.gg/epDPg4h7e9
